--------------------------------------------------------
--  Fichier créé - mercredi-janvier-06-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CARTEFID
--------------------------------------------------------

  CREATE TABLE "ROUKAIA"."CARTEFID" 
   (	"ID_CARTE" NUMBER, 
	"ID_CLIENT" NUMBER, 
	"DATE_CREATION_CARTE" DATE, 
	"NB_POINT" NUMBER, 
	"NB_FILM" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into ROUKAIA.CARTEFID
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index CARTEFID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROUKAIA"."CARTEFID_PK" ON "ROUKAIA"."CARTEFID" ("ID_CARTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CARTEFID
--------------------------------------------------------

  ALTER TABLE "ROUKAIA"."CARTEFID" MODIFY ("ID_CLIENT" NOT NULL ENABLE);
  ALTER TABLE "ROUKAIA"."CARTEFID" MODIFY ("ID_CARTE" NOT NULL ENABLE);
  ALTER TABLE "ROUKAIA"."CARTEFID" ADD CONSTRAINT "CARTEFID_PK" PRIMARY KEY ("ID_CARTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CARTEFID
--------------------------------------------------------

  ALTER TABLE "ROUKAIA"."CARTEFID" ADD CONSTRAINT "CARTEFID_FK1" FOREIGN KEY ("ID_CLIENT")
	  REFERENCES "ROUKAIA"."CLIENT" ("ID_CLIENT") ENABLE;
