--------------------------------------------------------
--  Fichier créé - mercredi-janvier-06-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CLIENT
--------------------------------------------------------

  CREATE TABLE "ROUKAIA"."CLIENT" 
   (	"ID_CLIENT" NUMBER, 
	"CIN" NUMBER(8,0), 
	"NOM" VARCHAR2(30 BYTE), 
	"PRENOM" VARCHAR2(30 BYTE), 
	"DATE_NAISSANCE" DATE, 
	"NUM_TEL" NUMBER(8,0), 
	"FONCTION" VARCHAR2(20 BYTE), 
	"ADRESSE" VARCHAR2(60 BYTE), 
	"DATE_CREATION" DATE, 
	"MAIL_CLIENT" VARCHAR2(70 BYTE), 
	"GENRE" VARCHAR2(7 BYTE), 
	"ETAT_CIVILE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into ROUKAIA.CLIENT
SET DEFINE OFF;
Insert into ROUKAIA.CLIENT (ID_CLIENT,CIN,NOM,PRENOM,DATE_NAISSANCE,NUM_TEL,FONCTION,ADRESSE,DATE_CREATION,MAIL_CLIENT,GENRE,ETAT_CIVILE) values ('11111111','11111111','roukaia','roukaia',to_date('26/12/20','DD/MM/RR'),'29043930','etudiante','adreess',to_date('26/12/20','DD/MM/RR'),'mailmailmail@jj.com','femme','celibataire');
--------------------------------------------------------
--  DDL for Index CLIENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROUKAIA"."CLIENT_PK" ON "ROUKAIA"."CLIENT" ("ID_CLIENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CLIENT
--------------------------------------------------------

  ALTER TABLE "ROUKAIA"."CLIENT" MODIFY ("ID_CLIENT" NOT NULL ENABLE);
  ALTER TABLE "ROUKAIA"."CLIENT" MODIFY ("CIN" NOT NULL ENABLE);
  ALTER TABLE "ROUKAIA"."CLIENT" ADD CONSTRAINT "CLIENT_PK" PRIMARY KEY ("ID_CLIENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
