--------------------------------------------------------
--  Fichier créé - mercredi-janvier-06-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table FILM
--------------------------------------------------------

  CREATE TABLE "ROUKAIA"."FILM" 
   (	"ID_FILM" NUMBER, 
	"NOM_FILM" VARCHAR2(30 BYTE), 
	"REALISATEUR" VARCHAR2(30 BYTE), 
	"NATIONALITE" VARCHAR2(20 BYTE), 
	"DATE_SORTIE" DATE, 
	"DISPONIBILITE" DATE, 
	"CATEGORIES" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into ROUKAIA.FILM
SET DEFINE OFF;
Insert into ROUKAIA.FILM (ID_FILM,NOM_FILM,REALISATEUR,NATIONALITE,DATE_SORTIE,DISPONIBILITE,CATEGORIES) values ('1','nom','hhhhhh','FRANCAIS',to_date('01/01/20','DD/MM/RR'),to_date('14/09/20','DD/MM/RR'),'ACTION');
--------------------------------------------------------
--  DDL for Index FILM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROUKAIA"."FILM_PK" ON "ROUKAIA"."FILM" ("ID_FILM", "NOM_FILM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FILM_PK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROUKAIA"."FILM_PK1" ON "ROUKAIA"."FILM" ("ID_FILM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table FILM
--------------------------------------------------------

  ALTER TABLE "ROUKAIA"."FILM" ADD CONSTRAINT "FILM_PK" PRIMARY KEY ("ID_FILM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ROUKAIA"."FILM" MODIFY ("NOM_FILM" NOT NULL ENABLE);
  ALTER TABLE "ROUKAIA"."FILM" MODIFY ("ID_FILM" NOT NULL ENABLE);
