--------------------------------------------------------
--  Fichier créé - mercredi-janvier-06-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SALLE
--------------------------------------------------------

  CREATE TABLE "ROUKAIA"."SALLE" 
   (	"NUMSALLE" NUMBER, 
	"NBCHAISE" NUMBER, 
	"NBBAFFLES" NUMBER, 
	"NBECRANS" NUMBER, 
	"DISPO" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into ROUKAIA.SALLE
SET DEFINE OFF;
Insert into ROUKAIA.SALLE (NUMSALLE,NBCHAISE,NBBAFFLES,NBECRANS,DISPO) values ('44','10','112','3','Salle Disponible');
Insert into ROUKAIA.SALLE (NUMSALLE,NBCHAISE,NBBAFFLES,NBECRANS,DISPO) values ('1','2','5','5','Salle Disponible');
Insert into ROUKAIA.SALLE (NUMSALLE,NBCHAISE,NBBAFFLES,NBECRANS,DISPO) values ('54','5','5','5','Salle Disponible');
Insert into ROUKAIA.SALLE (NUMSALLE,NBCHAISE,NBBAFFLES,NBECRANS,DISPO) values ('5','2','2','2','Salle Disponible');
Insert into ROUKAIA.SALLE (NUMSALLE,NBCHAISE,NBBAFFLES,NBECRANS,DISPO) values ('15','5','2','2','Salle Disponible');
--------------------------------------------------------
--  DDL for Index SYS_C007060
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROUKAIA"."SYS_C007060" ON "ROUKAIA"."SALLE" ("NUMSALLE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table SALLE
--------------------------------------------------------

  ALTER TABLE "ROUKAIA"."SALLE" ADD PRIMARY KEY ("NUMSALLE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
